baseURL: "/"

theme: PaperMod

paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

markup:
    highlight:
        style: rrt

outputs:
    home:
        - HTML
        - RSS
        - JSON

taxonomies:
    tag: tags
    series: series

title: gbiz.dev
defaultContentLanguage: ru

languages:
    ru:
        languageName: "Russian"
        weight: 1

        menu:
            main:
                - name: Архив
                  url: archives
                  weight: 1
                - name: Теги
                  url: tags
                  weight: 2
                - name: Поиск
                  url: search
                  weight: 3

        profileMode:
            enabled: false
            title: PaperMod
            imageUrl: "#"
            imageTitle: my image
            # imageWidth: 120
            # imageHeight: 120
            buttons:
                - name: Archives
                  url: archives
                - name: Tags
                  url: tags

        homeInfoParams:
            Title: "gbiz.dev"
            Content: >
              Aliquam sed accumsan neque, non tincidunt est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla facilisi. Proin laoreet ultricies ligula vel gravida. Mauris mauris sapien, cursus nec mollis a, luctus et tortor. Nam pellentesque enim at scelerisque fringilla. Donec sollicitudin risus eu erat vulputate, id congue ligula ullamcorper. Ut urna dui, pretium vitae auctor eget, cursus non nunc.

params:
    env: production
    description: "Блог griashiro"
    author: griashiro
    images: []

    defaultTheme: auto
    comments: false

    disableSpecial1stPost: true
    ShowReadingTime: true
    ShowBreadCrumbs: false
    ShowPostNavLinks: false
    ShowCodeCopyButtons: true
    ShowToc: true

    socialIcons:
        - name: github
          url: "https://github.com/griashiro"
        - name: RSS
          url: "index.xml"

    editPost:
        URL: "https://github.com/griashiro/gbiz.dev/tree/main/content"
        Text: "Предложить изменения"
        appendFilePath: true

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]
